### ISSUE TITLE
multiple command call by one b3 command

### ISSUE THREAD

**Issue by dilushan** [thomasleveil/b3-plugin-customcommands#3]
This is not an issue. But i wanted to know whether is it possible or not call multiple rcon commands from one b3 commands. All the examples in readme shows one to one relationship. But i want to call many rcon commands from one b3 command. Is it possible. What is the syntax if possible?

**Comment by thomasleveil** [comment]
No idea if it would work (it might depend on the game), but try separating commands with `;`

    sry = tell <LAST_VICTIM:PID> sorry mate :|; tell <LAST_VICTIM:PID> really sorry

**Comment by danielepantaleone** [comment]
It won't work on ioq3 engine based games at least. I don't know about the syntax but commands needs to be separated by something like 1500ms. Maybe we could split such string plugin side, and send separate commands to the server.

**Comment by dilushan** [comment]
I setup b3 for COD4. I tried thomasleveil suggestoin with few modification.  

test = tell <PLAYER:PID> sorry mate :|; tell <PLAYER:PID> really sorry

what it prints is

sorry mate :|; tell 0 really sorry

**Comment by thomasleveil** [comment]
Can't you create commandsin  the cod4 server config?

**Comment by dilushan** [comment]
No. According to my knowledge not possible

**Comment by thomasleveil** [comment]
There is nothing in this plugin that would allow to call multiple commands. This plugin was designed for very simple use cases

**Comment by dilushan** [comment]
understood. So I guess only if game allowed to call multiple commands in same line like u suggested before, its working. Am i right? is COD4 ioq3 engine based?

**Comment by danielepantaleone** [comment]
>>> is COD4 ioq3 engine based?
Yes

**Comment by dilushan** [comment]
All clear. I will close the issue.
